### ISSUE TITLE
Questions on the DCC reissue feature

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/certification-apis#231]
## Your Question

* PR: https://github.com/corona-warn-app/cwa-app-ios/pull/4271
* Question: Why is such a long time storage (1 year) of the generated hash necessary? Could you elaborate what abuse scenario this prevents?

I was asked to open this issue here instead of in https://github.com/corona-warn-app/cwa-documentation/issues/862 by @thomasaugsten.

**Comment by timokoenig** [comment]
Is there any documentation available for that feature, like what data is being used for the hash?

**Comment by Ein-Tim** [comment]
@timokoenig 

The best text is probably in https://github.com/corona-warn-app/cwa-app-ios/pull/4231.

**Comment by timokoenig** [comment]
@Ein-Tim I saw that and that's the reason I asked. The problem I saw is that it says "Temporary storage of the hash value of the signature of an **updated** certificate". The signature of the updated certificate should always be different and this results in a new hash. How does this prevent the "abuse"?

I would love to see some documentation of the whole process

**Comment by Ein-Tim** [comment]
Yeah it would be great if there would be documentation of new features... 😅

**Comment by vaubaehn** [comment]
> @Ein-Tim I saw that and that's the reason I asked. The problem I saw is that it says "Temporary storage of the hash value of the signature of an **updated** certificate". The signature of the updated certificate should always be different and this results in a new hash. How does this prevent the "abuse"?
> 
> I would love to see some documentation of the whole process

@timokoenig 
That's eagle-eyed...
I always read that part like "temporary storage of the hash value of the certificate **to be updated**...", because also for me it doesn't make any sense to store the hash of the updated certificate. If the abuse you want to stop is (D)DoS, then you effectively want to save CPU time by not again reissuing what has already be reissued before. For this you would need to store the hash of the DCC that needs to be updated.

While writing this, one scenario comes to my mind where one could nag other users whose DCCs had been leaked via social media:
For some time, I "hunted" publicly disclosed valid DCCs of real people, to inform picture agencies about some of their photographers to publish personal data of people (sometimes relatives) who do not know that their data is shared publicly.
With the hash blockage of DCCs it would be possible to reissue leaked DCCs certificates as soon after the reissuance service is accessable, preventing the "real" people to do so when they need to do so (i.e., technical expiry of necessary older DCCs like recovery DCCs)...

By the way: your Covid Validator is awesome! Very nice work, thank you!

**Comment by vaubaehn** [comment]
> I could even think of other scenarios, like a technical error in the app that failed to save the reissued certificate. Another very likely and inconvenient case is when a user changes the device and did not export the new reissued certificate. Due to the fact that the iCloud backup is disabled he is now left with the old, maybe expired, certificates that are unable to be reissued.
> 
> A pure (D)DoS prevention is not a justification to save the hash for a whole year. This could be reduced to maybe hours or a day.
> 
> I have so many open questions but I guess this is only because I have neither seen the final implementation nor a documentation.

@timokoenig 
These are all valid points, and my gut feeling is that it might be worth to reevaluate the threshold of 365 days for blocking the hash (be it updated certificate or certificate to be updated).
Even when for the likely soon starting roll out the 365 day value may be fixed, all app teams should be prepared for public announcements regarding this issue and for a possible change.
So I hope, everyone is fine when I'm pinging the responsible, to create a shared attention on this subject:
@thinkberg @mlenkeit @oliver-steinbrecher (don't know if reissuing is planned for CovPass)

**Comment by timokoenig** [comment]
I just saw this PR https://github.com/Digitaler-Impfnachweis/covpass-apps-i18n/pull/178/files and this confirms that CovPass also implements this feature

**Comment by mlenkeit** [comment]
> So I hope, everyone is fine when I'm pinging the responsible, to create a shared attention on this subject:
> @thinkberg @mlenkeit @oliver-steinbrecher (don't know if reissuing is planned for CovPass)

I think that's something that would need to be answered by @thinkberg or @oliver-steinbrecher

**Comment by vaubaehn** [comment]
@thinkberg 
There are actually three seperate questions that arose when reviewing the privacy notice that will be changed for CWA 2.19:
- The hashes of which certificate is to be stored? The hash for the certificate to be updated or the hash for the updated certificate?
- a corrected version of the new privacy note handles _two_ different types of DCCs that are returned to the wallet up: an updated DCC and a new DCC - is this actually true or a misunderstanding in CWA's legal department? And in case it's true - what are the differences between updated/new DCC?
- Are you actually storing the hash 365 days? Or is this value to be changed?

We (as in "the user community of the CWA") consider that CWA 2.19 is soon to be rolled out. The privacy note could be a blocker, when there are still wrong information contained. So we would be very happy, if you could respond in a timely manner.
Thanks in advance!

**Comment by timokoenig** [comment]
I just came across a few important questions regarding the reissue feature:

When the user reissues the certificate, does the UVCI of the given certificate change? If YES, does the API check for all certificates that CovPass already invalidated? If the API does not check for those certificates, the user with an invalidated certificate could simply reissue it to receive a valid certificate again.

How does the API know what needs to be changed in the certificate? Is there a fixed rule set or does the client marks the changes? I hope it's not the last options, otherwise it could open a big door for potential manipulation.

Since I haven't received any feedback, will the reissue service be open source and/or will there be a documentation?

**Comment by oliver-steinbrecher** [comment]
@thinkberg can you share the api and supported use cases here ?

**Comment by oliver-steinbrecher** [comment]
API Spec: https://github.com/Digitaler-Impfnachweis/certification-apis/blob/master/dcc-reissue-api.yaml

**Comment by timokoenig** [comment]
The specs also describe the use case `re-issues a new certificate with a different validity`. I thought based on previous comments that this hasn't been implemented?

**Comment by oliver-steinbrecher** [comment]
The spec needs to be updated - the description is misleading. @thinkberg will take care of this. We’re going to exchange misleading certificates to the new 2/1 encoding which is mandatory since February

**Comment by timokoenig** [comment]
@oliver-steinbrecher thank you for the clarification 👍🏼

**Comment by Ein-Tim** [comment]
This issue is resolved.
